### ISSUE TITLE
唐兄，手指影视源很不错，可惜失效了，能否百忙中修复一下。

### ISSUE THREAD

**Issue by pglblb** [Tangsan99999/cat#2]
"key": "csp_appys_v1_手指影视",
      "name": "手指影视",
      "type": 3,
      "api": "csp_AppYs",
      "searchable": 1,
      "quickSearch": 1,
      "filterable": 1,
      "ext": "v1_手指影视"

**Comment by Tangsan99999** [comment]
AppYs我不会搞，要问官方瓜神

**Comment by pglblb** [comment]
感谢。
