### ISSUE TITLE
寄唐兄的一点小建议

### ISSUE THREAD

**Issue by pglblb** [Tangsan99999/cat#3]
唐兄好，这段时间测试过你public公布过的所有源，用的jar包有litecucumber\官方catvod\以及你public目录下的jar配置包，目前只有爱西西（p）\365影视、阿房、2345、瓜皮TV等可以通过。其他如Gimy、Jumi、sky4K、唐人街都没办法测试通过。特别是唐人街、sky4K好像你做了有几天了，我也测试了十几轮，未能通过，不知道唐兄用的是你自己的那个jar包。
个人有个小建议：
1、建议改编维护好原有的优秀源如天空影视、雪人影视、狐狸影视、爱西西、疯狂看、二狗电影等为已所用（具体可参考我的对外链接搜索源排行：http://gg.gg/maotv，结合开发优秀的个性源。像天空4K、独播库这类源后续研究开发没有多大意义，速度慢或有菠菜广告，价值大打折扣。
2、类似需要口令的解析或破解地址，容易失效，维护难度太大，有时玩玩可以，如果时效性不长，其他客户端维护起来不仅需要点小技术，还要时间，没有实用价值。
我爱玩影视软件 ，懂电脑但不懂任何编程，以上建议不到之处多包涵。

祝顺利！

2021.12.06

**Comment by Tangsan99999** [comment]
我jar里大多数都是海外比较顺，国内就用瓜瓜大神的吧，我很少搞新源，也就周末能用几个小时电脑整理整理，平时都用手机维护而已，能用就好。
