### ISSUE TITLE
关于播放源解码的问题求教。

### ISSUE THREAD

**Issue by pglblb** [Tangsan99999/cat#4]
唐兄，有时间能否研究一下能否在jar文件或配置文件解决类似
      "key": "libvio",
      "name": "libvio",
      "type": 0,
      "api": "https://www.libvio.com/api.php/provide/vod/at/xml"
（可搜索如“致命感应”看到播放源）
播放源line400、xulei1以及789pan、miaoparty无法解码播放的问题。

**Comment by Tangsan99999** [comment]
网站作者没维护问题

**Comment by pglblb** [comment]
我测试过PC端所有的源播放都很流畅，没有问题，不确定是解码还是数据采集后播放限制问题。这个网站的源还是不错的，有点类似“低端影视https://ddrk.me”，看以后有没机会能做成猫影视资源。

**Comment by Tangsan99999** [comment]
你说的我都帮不了你，有些网站没本事搞，需要瓜神那种更厉害的人才会写。能搞的网站，我却没时间折腾，加密或需要解码的更不用说了。
我现在已经不搞了，白嫖官方就够了。
花个十分钟写个xpath还行。

**Comment by pglblb** [comment]
谢谢。
